CREATE TABLE IF NOT EXISTS Accounts(
    ID int UNSIGNED NOT NULL AUTO_INCREMENT,
    BALANCE DECIMAL(10,2) NOT NULL,
    ClientsID VARCHAR(15) NOT NULL,
    PRIMARY KEY(ID),
    Foreign Key (ClientsID) REFERENCES clientes (CPF)


)